# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'In-App-PurchaseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for In-App-PurchaseDemo

  pod 'SwiftyStoreKit'
  pod 'SwiftyJSON'

end
